### ISSUE TITLE
onPreviewFrame data + OpenCV 实时处理的问题

### ISSUE THREAD

**Issue by ShaunXia** [wuhaoyu1990/MagicCamera#1]
你好，我也在相同的东西，除了实时滤镜之外，我还需要用OpenCV 做一些 识别算法，然后再实时GL 渲染。
所以不能用 Shader 直接进行 YUV2RGB的操作。 // 这里我不知道行不行，刚刚接触GL？

目前采用的是 JNI中进行 YUV2RGB 操作，然后进行 内容识别，GLSurfaceView中进行渲染，根据返回的识别的物体 坐标点 实时 进行贴图。  // 这样是否有效率问题？

在进行实时贴图时，与实际坐标有很大偏差，不知道你是否有类似的经验。 

Thanks.

**Comment by wuhaoyu1990** [comment]
可以不在shader里转换，在jni中转换就行，好像采用汇编最快。
关于坐标问题这个我也没有类似经验，抱歉，

**Comment by ShaunXia** [comment]
已经用NEON加速了，感觉还是有点慢，可能是JAVA 和 JNI 传输的问题，准备改成 DirectBuffer.
看到 GPUImage 似乎现在也使用Shader了，里面的那个YUV2RGB的 JNI 好像已经不调用了。 

我看到你的这个里面也没有调onPreviewFrame，应该是没对原始数据进行处理的吧，直接上GL Shader进行滤镜计算的？

Thanks.

**Comment by wuhaoyu1990** [comment]
恩,我是将surfacetexture与gl绑定来绘制，如果需要滤镜就绘制到framebuffer再经过一次shader

**Comment by ab503044120** [comment]
@ShaunXia 请问下neon加速要怎么实现呢
