### ISSUE TITLE
两个滤镜黑屏出错

### ISSUE THREAD

**Issue by stdzhu** [wuhaoyu1990/MagicCamera#3]
在用 美肤 和 美白 这两个滤镜的时候，一只黑屏，下面着两行log重复打印
01-27 18:03:20.934 13044-13122/com.seu.magiccamera W/Adreno-ES20: <core_glVertexAttribPointer:533>: GL_INVALID_VALUE
01-27 18:03:20.967 13044-13122/com.seu.magiccamera W/GLConsumer: [unnamed-13044-0] bindTextureImage: clearing GL error: 0x501
求解决。

**Comment by wuhaoyu1990** [comment]
好的,谢谢，我是华为mate7，可以运行，我去找下别的手机试试

**Comment by stdzhu** [comment]
你好，我又试了这几台手机：红米1s、红米note1、小米3、1加、mx4pro、s6，
其中mx4pro和s6能用，这两台都是三星的cpu。

**Comment by wuhaoyu1990** [comment]
我猜测可能是低端手机模糊半径要调小一点，需要写一个方法根据gpu判断，我明天写写看.

**Comment by wuhaoyu1990** [comment]
现在应该不会黑屏了，不过低端机应该会卡顿，相应调低了低端机的效果，但没有囊括所有GPU型号，以后慢慢添加..

**Comment by stdzhu** [comment]
可以运行了，多谢多谢。
