### ISSUE TITLE
gradle  loop error 重复反复的错误 不用这个框架没问题 ，以前也没事 现在是循环的报错了。

### ISSUE THREAD

**Issue by lozn00** [wuhaoyu1990/MagicCamera#34]
Error:Gradle version 2.10 is required. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl in E:\dev\meifa_1\gradle\wrapper\gradle-wrapper.properties to gradle-2.10-all.zip.

Please fix the project's Gradle settings.
<a href="fixGradleVersionInWrapper">Fix Gradle wrapper and re-import project</a><br><a href="openGradleSettings">Gradle settings</a>

**Comment by zpf527** [comment]
you can try:
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle-experimental:0.7.3"

```
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}
```

}
