### ISSUE TITLE
关于MagicBeautyFilter中一行代码的问题^_^

### ISSUE THREAD

**Issue by orange2003** [wuhaoyu1990/MagicCamera#5]
我在准备一直iOS的过程中查看MagicBeautyFilter的代码发现在setBeautyLevel 函数中有一句
case 2:
			setFloatVec3(mParamsLocation, new float[] {0.8f, 0.9f, 0.2f, 0.2f});
但是在后面的float 数组中给的是四个值。这里是否有错误？因为Vec3 应该只接受三个值吧

**Comment by orange2003** [comment]
另外补充一个问题MagicBeautyFilter中的这个函数  onOutputSizeChanged 是不是对应了GPUImage 中GPUImageOutput 里的 
/// @name Manage the output texture

- (void)forceProcessingAtSize:(CGSize)frameSize;
- (void)forceProcessingAtSizeRespectingAspectRatio:(CGSize)frameSize;
这两个函数中的一个呢请指教谢谢

**Comment by orange2003** [comment]
我已经移植完毕iOS效果不错晚上给我老婆评测下现在贴出代码请指正
`/
//  MagicBeautyFilter.m
//  SimpleVideoFilter
//
//  Created by GaoFei on 16/2/17.
//  Copyright © 2016年 Cell Phone. All rights reserved.
//

#import "MagicBeautyFilter.h"

@interface MagicBeautyFilter()
- (void)setTexelSize:(float)width height:(float)height;
@end


@implementation MagicBeautyFilter
int _mSingleStepOffsetLocation;
int _mParamsLocation;

NSString *const kMagicBeautyFilterShaderString = SHADER_STRING
(
 precision highp float;
 
 uniform sampler2D inputImageTexture;
 uniform vec2 singleStepOffset;
 uniform highp vec4 params;
 
 varying highp vec2 textureCoordinate;
 
 const highp vec3 W = vec3(0.299,0.587,0.114);
 const mat3 saturateMatrix = mat3(
                                  1.1102,-0.0598,-0.061,
                                  -0.0774,1.0826,-0.1186,
                                  -0.0228,-0.0228,1.1772);
 
 float hardlight(float color)
{
    if(color <= 0.5)
    {
        color = color * color * 2.0;
    }
    else
    {
        color = 1.0 - ((1.0 - color)*(1.0 - color) * 2.0);
    }
    return color;
}
 
 void main(){
     vec2 blurCoordinates[24];
     
     blurCoordinates[0] = textureCoordinate.xy + singleStepOffset * vec2(0.0, -10.0);
     blurCoordinates[1] = textureCoordinate.xy + singleStepOffset * vec2(0.0, 10.0);
     blurCoordinates[2] = textureCoordinate.xy + singleStepOffset * vec2(-10.0, 0.0);
     blurCoordinates[3] = textureCoordinate.xy + singleStepOffset * vec2(10.0, 0.0);
     
     blurCoordinates[4] = textureCoordinate.xy + singleStepOffset * vec2(5.0, -8.0);
     blurCoordinates[5] = textureCoordinate.xy + singleStepOffset * vec2(5.0, 8.0);
     blurCoordinates[6] = textureCoordinate.xy + singleStepOffset * vec2(-5.0, 8.0);
     blurCoordinates[7] = textureCoordinate.xy + singleStepOffset * vec2(-5.0, -8.0);
     
     blurCoordinates[8] = textureCoordinate.xy + singleStepOffset * vec2(8.0, -5.0);
     blurCoordinates[9] = textureCoordinate.xy + singleStepOffset * vec2(8.0, 5.0);
     blurCoordinates[10] = textureCoordinate.xy + singleStepOffset * vec2(-8.0, 5.0);
     blurCoordinates[11] = textureCoordinate.xy + singleStepOffset * vec2(-8.0, -5.0);
     
     blurCoordinates[12] = textureCoordinate.xy + singleStepOffset * vec2(0.0, -6.0);
     blurCoordinates[13] = textureCoordinate.xy + singleStepOffset * vec2(0.0, 6.0);
     blurCoordinates[14] = textureCoordinate.xy + singleStepOffset * vec2(6.0, 0.0);
     blurCoordinates[15] = textureCoordinate.xy + singleStepOffset * vec2(-6.0, 0.0);
     
     blurCoordinates[16] = textureCoordinate.xy + singleStepOffset * vec2(-4.0, -4.0);
     blurCoordinates[17] = textureCoordinate.xy + singleStepOffset * vec2(-4.0, 4.0);
     blurCoordinates[18] = textureCoordinate.xy + singleStepOffset * vec2(4.0, -4.0);
     blurCoordinates[19] = textureCoordinate.xy + singleStepOffset * vec2(4.0, 4.0);
     
     blurCoordinates[20] = textureCoordinate.xy + singleStepOffset * vec2(-2.0, -2.0);
     blurCoordinates[21] = textureCoordinate.xy + singleStepOffset * vec2(-2.0, 2.0);
     blurCoordinates[22] = textureCoordinate.xy + singleStepOffset * vec2(2.0, -2.0);
     blurCoordinates[23] = textureCoordinate.xy + singleStepOffset * vec2(2.0, 2.0);
     
     
     float sampleColor = texture2D(inputImageTexture, textureCoordinate).g * 22.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[0]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[1]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[2]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[3]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[4]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[5]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[6]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[7]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[8]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[9]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[10]).g;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[11]).g;
     
     sampleColor += texture2D(inputImageTexture, blurCoordinates[12]).g * 2.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[13]).g * 2.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[14]).g * 2.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[15]).g * 2.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[16]).g * 2.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[17]).g * 2.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[18]).g * 2.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[19]).g * 2.0;
     
     sampleColor += texture2D(inputImageTexture, blurCoordinates[20]).g * 3.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[21]).g * 3.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[22]).g * 3.0;
     sampleColor += texture2D(inputImageTexture, blurCoordinates[23]).g * 3.0;
     
     sampleColor = sampleColor / 62.0;
     
     vec3 centralColor = texture2D(inputImageTexture, textureCoordinate).rgb;
     
     float highpass = centralColor.g - sampleColor + 0.5;
     
     for(int i = 0; i < 5;i++)
     {
         highpass = hardlight(highpass);
     }
     float lumance = dot(centralColor, W);
     
     float alpha = pow(lumance, params.r);
     
     vec3 smoothColor = centralColor + (centralColor-vec3(highpass))*alpha*0.1;
     
     smoothColor.r = clamp(pow(smoothColor.r, params.g),0.0,1.0);
     smoothColor.g = clamp(pow(smoothColor.g, params.g),0.0,1.0);
     smoothColor.b = clamp(pow(smoothColor.b, params.g),0.0,1.0);
     
     vec3 lvse = vec3(1.0)-(vec3(1.0)-smoothColor)*(vec3(1.0)-centralColor);
     vec3 bianliang = max(smoothColor, centralColor);
     vec3 rouguang = 2.0*centralColor*smoothColor + centralColor*centralColor - 2.0*centralColor*centralColor*smoothColor;
     
     gl_FragColor = vec4(mix(centralColor, lvse, alpha), 1.0);
     gl_FragColor.rgb = mix(gl_FragColor.rgb, bianliang, alpha);
     gl_FragColor.rgb = mix(gl_FragColor.rgb, rouguang, params.b);
     
     vec3 satcolor = gl_FragColor.rgb * saturateMatrix;
     gl_FragColor.rgb = mix(gl_FragColor.rgb, satcolor, params.a);
 }
);

#pragma mark -
#pragma mark Initialization and teardown

- (id)init;
{
    if (!(self = [self initWithFragmentShaderFromString:kMagicBeautyFilterShaderString]))
    {
        return nil;
    }
    _mSingleStepOffsetLocation = [filterProgram uniformIndex:@"singleStepOffset"];
    _mParamsLocation = [filterProgram uniformIndex:@"params"];
    self.beautyLevel = 4;
    return self;
}

- (void)setupFilterForSize:(CGSize)filterFrameSize;
{
    [self setTexelSize:filterFrameSize.width height:filterFrameSize.height];
}

- (void)setTexelSize:(float)width height:(float)height
{
    [self setPoint:CGPointMake(2.0/width, 2.0/height) forUniform:_mSingleStepOffsetLocation program:filterProgram];
}

- (void)setBeautyLevel:(int)beautyLevel
{
    if (_beautyLevel!=beautyLevel) {
        _beautyLevel = beautyLevel;
        switch (_beautyLevel) {
            case 0:
                [self setVec4:(GPUVector4){1.0f, 1.0f, 0.15f, 0.15f} forUniform:_mParamsLocation program:filterProgram];
                break;
            case 1:
                [self setVec4:(GPUVector4){0.8f, 0.9f, 0.2f, 0.2f} forUniform:_mParamsLocation program:filterProgram];
                break;
            case 2:
                [self setVec4:(GPUVector4){0.6f, 0.8f, 0.25f, 0.25f} forUniform:_mParamsLocation program:filterProgram];
                break;
            case 3:
                [self setVec4:(GPUVector4){0.4f, 0.7f, 0.38f, 0.3f} forUniform:_mParamsLocation program:filterProgram];
                break;
            case 4:
                [self setVec4:(GPUVector4){0.33f, 0.63f, 0.4f, 0.35f} forUniform:_mParamsLocation program:filterProgram];
                break;
            default:
                break;
        }
    }
}
@end`

**Comment by wuhaoyu1990** [comment]
我不懂ios - - ||抱歉...

**Comment by orange2003** [comment]
基本都差不多。只是方法名有些变化但是你确定在你的代码里面 
case 2:
setFloatVec3(mParamsLocation, new float[] {0.8f, 0.9f, 0.2f, 0.2f}); 这样写没问题吗？

**Comment by wuhaoyu1990** [comment]
这个是手误，应该是setFloatVec4，谢谢指正~

**Comment by gaopeipeiok** [comment]
您好，我现在也在移植到ios里面，遇到了些问题，能否请教下：
MagicBeautyFilter这个继承了那个类呢，GPUImage吗？
uniform sampler2D inputImageTexture;和varying highp vec2 textureCoordinate;都不用初始化吗？

(void)setupFilterForSize:(CGSize)filterFrameSize;这个是基类的接口吗？

**Comment by wuhaoyu1990** [comment]
MagicBeautyFilter继承了GPUImageFilter
那两个的初始化过程在GPUImageFilter里
setupFilterForSize，filterFrameSize应该是IOS的GPUImage的接口吧

**Comment by gaopeipeiok** [comment]
找到了，谢谢哈

**Comment by gaopeipeiok** [comment]
你已经移植完了吗？能否发给我学习学习呢

**Comment by gaopeipeiok** [comment]
哈哈 我也移植完啦 谢谢
