### ISSUE TITLE
将shader脚本移到ios里面黑屏

### ISSUE THREAD

**Issue by gaopeipeiok** [wuhaoyu1990/MagicCamera#6]
我将cool.glsl里面的算法copy到iOS里面，预览黑屏。能麻烦看看是什么问题吗？我已有的灰度算法是正常的。
const char * const
    GlowVideoFilter::pixelKernel() const
    {
        KERNEL(GL_ES2_3, m_language,
               varying highp vec2 textureCoordinate;
precision highp float;

uniform sampler2D inputImageTexture;
uniform sampler2D curve;

void main()
{ 
	lowp vec4 textureColor;
	lowp vec4 textureColorOri;
	
	float xCoordinate = textureCoordinate.x;
	float yCoordinate = textureCoordinate.y;
	
	highp float redCurveValue;
	highp float greenCurveValue;
	highp float blueCurveValue;
	
	textureColor = texture2D( inputImageTexture, vec2(xCoordinate, yCoordinate));
	textureColorOri = textureColor;
	// step1 curve 
	redCurveValue = texture2D(curve, vec2(textureColor.r, 0.0)).r;
	greenCurveValue = texture2D(curve, vec2(textureColor.g, 0.0)).g;
	blueCurveValue = texture2D(curve, vec2(textureColor.b, 0.0)).b;
	// step2 level
	redCurveValue = texture2D(curve, vec2(redCurveValue, 0.0)).a;
	greenCurveValue = texture2D(curve, vec2(greenCurveValue, 0.0)).a;
	blueCurveValue = texture2D(curve, vec2(blueCurveValue, 0.0)).a;
	// step3 brightness/constrast adjust 
	redCurveValue = redCurveValue * 1.25 - 0.12549;
	greenCurveValue = greenCurveValue * 1.25 - 0.12549; 
	blueCurveValue = blueCurveValue * 1.25 - 0.12549;
	//redCurveValue = (((redCurveValue) > (1.0)) ? (1.0) : (((redCurveValue) < (0.0)) ? (0.0) : (redCurveValue)));
	//greenCurveValue = (((greenCurveValue) > (1.0)) ? (1.0) : (((greenCurveValue) < (0.0)) ? (0.0) : (greenCurveValue)));
	//blueCurveValue = (((blueCurveValue) > (1.0)) ? (1.0) : (((blueCurveValue) < (0.0)) ? (0.0) : (blueCurveValue)));
	// step4 normal blending with original
	textureColor = vec4(redCurveValue, greenCurveValue, blueCurveValue, 1.0);
	textureColor = (textureColorOri - textureColor) * 0.549 + textureColor;
	
	gl_FragColor = vec4(textureColor.r, textureColor.g, textureColor.b, 1.0);
}
               )
        return nullptr;
    }

已有的灰度滤镜：
const char * const
    GrayscaleVideoFilter::pixelKernel() const
    {
        
         KERNEL(GL_ES2_3, m_language,
               precision mediump float;
               varying vec2      vCoord;
               uniform sampler2D uTex0;
               void main(void) {
                   vec4 color = texture2D(uTex0, vCoord);
                   float gray = dot(color.rgb, vec3(0.3, 0.59, 0.11));
                   gl_FragColor = vec4(gray, gray, gray, color.a);
               }
        )
        
        return nullptr;
    }

**Comment by gaopeipeiok** [comment]
I find how to deal singleStepOffset and params, but cannot find how to deal inputImageTexture and textureCoordinate. who can tell me how to deal the two values?
mSingleStepOffsetLocation = GLES20.glGetUniformLocation(getProgram(), "singleStepOffset"); mParamsLocation = GLES20.glGetUniformLocation(getProgram(), "params");
setFloatVec2(mSingleStepOffsetLocation, new float[] {2.0f / w, 2.0f / h});
setFloatVec4(mParamsLocation, new float[] {0.33f, 0.63f, 0.4f, 0.35f});

**Comment by wuhaoyu1990** [comment]
我不知道IOS的在哪里，Android的在GPUImageFilter的onInit里

**Comment by gaopeipeiok** [comment]
哈哈 解决了 非常感谢
